site_name: My Docs

theme:
  name: material
  logo: assets/images/logo.png

nav:
  - Accueil: index.md
  - SP3 Mission 1: SP3-Mission1.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
